#!/bin/sh
#
# chkpkglists - Quick utility to make sure we aren't duplicating
#               packages in more than one module.
#
PKGLISTS=$( find . -name pkglist )
[ -z ${PKGLISTS} ] && {
    echo "Cannot find any pkglist files under this directory tree."
    exit 1
}

for list in $PKGLISTS ; 
do
 PACKAGES=$( egrep -v "^#|^$" $list | cut -d'#' -f1 )
 for name in $PACKAGES;
 do
   grep -Hi ${name} ${PKGLISTS//${list}//} || exit 1
   echo "Found duplicate in $list."
 done;
done;
