#!/bin/sh -e

TMP=${TMP:-/tmp}

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi

# java perl not included yet
BUILD_ORDER="c++
python"

(
for i in $BUILD_ORDER
do
(
  cd $i
  echo ""
  echo "*************************************************"
  echo "*****         Building $i"
  echo "*************************************************"
  echo ""
  ./gnome.$i.bindings.SlackBuild
)
done
# Fork screen output to a log
) 2>&1 | tee $TMP/gnome.platform.build.log
