#!/bin/sh

BUILDCWD=`pwd`
TMP=${TMP:-/tmp}
BASE_DL_URL="http://enlightenment.freedesktop.org/fetch.php?file="
PKGS="
edb-1.0.5.004.tar.gz
eet-0.9.10.014.tar.gz
evas-0.9.9.014.tar.gz
ecore-0.9.9.014.tar.gz
embryo-0.9.1.014.tar.gz
imlib2-1.2.1.005.tar.gz
edje-0.5.0.014.tar.gz
ewl-0.0.4.004.tar.gz
epeg-0.9.0.004.tar.gz
epsilon-0.3.0.004.tar.gz
emotion-0.0.1.004.tar.gz
esmart-0.9.0.004.tar.gz
entrance-0.9.0.004.tar.gz
enlightenment-0.16.999.014.tar.gz
entice-0.9.3.004.tar.gz
etox-0.9.0.004.tar.gz
imlib2_loaders-1.2.1.005.tar.gz"

echo '' > e17.log

slapt-get --remove --no-dep eet evas ecore embryo imlib2 edje ewl epeg epsilon esmart edb entrance enlightenment emotion entice etox imlib2_loaders 2>&1 | tee -a e17.log

for pkg in $PKGS
do
  DIR=$(echo $pkg|sed -re "s/-[0-9].*//")
  VERSION=$(echo $pkg|sed -re "s/.*-([0-9].*).tar.gz/\1/")
  sed -i -re "s/VERSION=.*/VERSION=$VERSION/" $DIR/${DIR}.SlackBuild
  (
    cd $DIR
    wget -c ${BASE_DL_URL}${pkg}
    (./$DIR.SlackBuild && upgradepkg --install-new $TMP/${DIR}-*.tgz) || kill $$
  ) 2>&1 | tee -a $BUILDCWD/e17.log
done

