#!/bin/sh

TMP=${TMP:-/tmp}

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi

BUILD_ORDER="ruby
ruby-gnome2-all"

(
for i in $BUILD_ORDER
do
(
  cd $i
  echo ""
  echo "*************************************************"
  echo "*****         Building $i"
  echo "*************************************************"
  echo ""
  ./$i.SlackBuild
  upgradepkg --install-new $TMP/$i*.tgz
)
done
# Fork screen output to a log
) 2>&1 | tee $TMP/gnome.ruby.bindings.build.log
