#!/usr/bin/env bash

#
#  +--------------------------------------------------------------------+
#  | Freerock GNOME installer script                                    |
#  | (c) 2005 Chip Cuccio <http://gsb.freerock.org/>                    |
#  | This progam is distributed under the GNU GPL;                      |
#  |   See <http://www.gnu.org/licenses/gpl.html> for lic. info         |
#  |--------------------------------------------------------------------|
#  | $Id$               |
#  +--------------------------------------------------------------------+
#

FRG_VER="current"
SLAPTGET_VER="0.9.9m-i486-1frg"
SLAPTGET_FILE="slapt-get-$SLAPTGET_VER.tgz"
TMP="/tmp"
MIRROR="http://mirror.datapipe.net/norlug/frg"
SLAPTGET_DLPATH="$MIRROR/frg-$FRG_VER/extras/other/$SLAPTGET_FILE"
TEMP_CONFIGFILE="$TMP/slapt-getrc"

#
# determine if r3wt
#
PROGUSER=`whoami`
if [ ${PROGUSER} != "root" ]; then
    clear
    echo
    echo "You must be root when running this program!"
    echo "log into a shell as root and run this command again;"
    echo 
    echo "     lynx --source http://gsb.freerock.org/net-install | sh"
    echo
    exit 1
fi

#
# set paths for binaries/libs/etc.
#
export PATH=$PATH:/usr/sbin:/usr/local/bin

clear
echo ""
echo "Preparing Freerock GNOME installation..."
echo ""
sleep 2
echo "
WORKINGDIR=/var/slapt-get
SOURCE=$MIRROR/frg-$FRG_VER" > $TEMP_CONFIGFILE

#
# is wget installed?
#
WGET=`which wget`
if [ ! -e "${WGET}" ]; then
    echo ""
    echo "wget must be installed to run this program"
    echo ""
    exit 1
fi

SLAPTGET_BIN=`which slapt-get`
if [ ! -e "${SLAPTGET_BIN}" ]; then
    echo ""
    echo "slapt-get not found. Downloading and installing..."
    echo ""
    sleep 2
    $WGET --progress=bar \
      $SLAPTGET_DLPATH -O $TMP/$SLAPTGET_FILE
    upgradepkg --install-new  $TMP/$SLAPTGET_FILE
    rm -f $TMP/$SLAPTGET_FILE
fi
sleep 2

echo ""
echo "Updating package lists..."
echo ""

slapt-get --config $TEMP_CONFIGFILE --update

echo ""
echo "Instaling/updating Freerock GNOME"...
echo ""

slapt-get --config $TEMP_CONFIGFILE --install frg-gnome-meta -y

slapt-get --config $TEMP_CONFIGFILE --clean

rm -f $TEMP_CONFIGFILE

echo ""
echo "Freerock GNOME has been installed!"
echo ""

exit
