#!/usr/bin/env bash

#
#  +--------------------------------------------------------------------+
#  | Freerock GNOME installer script                                    |
#  | (c) 2005 Chip Cuccio <http://gsb.freerock.org/>                    |
#  | This progam is distributed under the GNU GPL;                      |
#  |   See <http://www.gnu.org/licenses/gpl.html> for lic. info         |
#  |--------------------------------------------------------------------|
#  | $Id$               |
#  +--------------------------------------------------------------------+
#

FRG_VER="0.2.2"
SLAPTGET_VER="0.9.9m-i486-1frg"
SLAPTGET_FILE="slapt-get-$SLAPTGET_VER.tgz"
TMP="/tmp"
MIRROR="http://mirror.datapipe.net/norlug/frg/"
SLAPTGET_DLPATH="$MIRROR/frg-$FRG_VER/extras/other/$SLAPTGET_FILE"
TEMP_CONFIGFILE="$TMP/slapt-getrc"

#
# set paths for binaries/libs/etc.
#
export PATH=$PATH:/usr/sbin:/usr/local/bin

clear
echo ""
echo "Preparing Freerock GNOME installation..."
echo ""
sleep 2
echo "
WORKINGDIR=/var/slapt-get
SOURCE=$MIRROR/$FRG_VER" > $TEMP_CONFIGFILE

#
# is sudo installed?
#
SUDO=`which sudo`
if [ ! -e "${SUDO}" ]; then
    echo ""
    echo "sudo must be installed to run this program"
    echo ""
    exit 1
else
    $SUDO uname > /dev/null 2>&1 
fi

#
# is wget installed?
#
WGET=`which wget`
if [ ! -e "${WGET}" ]; then
    echo ""
    echo "wget must be installed to run this program"
    echo ""
    exit 1
fi

SLAPTGET_BIN=`which slapt-get`
if [ ! -e "${SLAPTGET_BIN}" ]; then
    echo ""
    echo "slapt-get not found. Downloading and installing..."
    echo ""
    sleep 2
    $WGET --progress=bar \
      $SLAPTGET_DLPATH -O $TMP/$SLAPTGET_FILE
    $SUDO upgradepkg --install-new  $TMP/$SLAPTGET_FILE
    $SUDO rm -f $TMP/$SLAPTGET_FILE
fi
sleep 2

echo ""
echo "Updating package lists..."
echo ""

$SUDO slapt-get --config $TEMP_CONFIGFILE --update

echo ""
echo "Instaling/updating Freerock GNOME"...
echo ""

$SUDO slapt-get --config $TEMP_CONFIGFILE --search \
  [0-9]frg$ | awk '{print $1}' | xargs -r slapt-get --install -y

$SUDO slapt-get --config $TEMP_CONFIGFILE --clean

$SUDO rm -f $TEMP_CONFIGFILE

echo ""
echo "Freerock GNOME has been installed!"
echo ""

exit
